export const tradingQuotes = [
  "Consistency compounds. Protect capital first.",
  "A good trader manages risk before chasing reward.",
  "Your strategy creates the opportunity. Your discipline captures it.",
  "The goal is not to trade more. It is to trade better.",
  "Protecting capital keeps tomorrow's opportunity alive.",
  "A missed trade costs less than a bad trade.",
  "Trade the setup you planned, not the outcome you want.",
  "Discipline is executing the same edge when emotions say otherwise.",
  "Your best trade is often the one you had the discipline to avoid.",
  "Risk small enough that your next decision stays rational.",
  "A losing trade is information. Repeating the same mistake is a choice.",
  "The market does not reward urgency. It rewards execution.",
  "Your edge means little without consistent execution.",
  "Patience is part of the strategy, not a break from it.",
  "A trader's results reveal their habits long before their potential.",
  "One disciplined trade can teach more than ten impulsive ones.",
  "You cannot control the market. You can control your response to it.",
  "Protect your downside and give your edge room to work.",
  "Good trading is often the discipline to do nothing.",
  "The trade ends when the plan says it ends, not when emotion does.",
  "Consistency is built when nobody is watching.",
  "Your journal should explain your decisions, not just your results.",
  "Profit measures the outcome. Process explains it.",
  "Every trade is a vote for the trader you are becoming.",
  "A strategy without discipline is only a theory.",
  "The market can take your money. It should not take your discipline.",
  "Do not confuse activity with progress.",
  "The objective is not to predict everything. It is to execute your edge.",
  "A controlled loss is part of the business.",
  "Your risk defines how long you get to participate.",
  "The best traders respect the trade they cannot see.",
  "If the setup is not there, the trade is not there.",
  "Strong conviction does not justify weak risk management.",
  "The market owes you nothing after a losing trade.",
  "A winning streak tests your discipline differently than a losing streak.",
  "Confidence should come from preparation, not recent profits.",
  "Do not let one winning trade rewrite your entire strategy.",
  "Do not let one losing trade rewrite it either.",
  "Your job is to execute the plan. The market decides the result.",
  "Risk management turns uncertainty into something you can survive.",
  "A trader who cannot wait cannot consistently execute.",
  "The quality of your decisions matters more than the quantity of your trades.",
  "The chart gives you possibilities. Discipline determines your actions.",
  "The trade you force today can become tomorrow's lesson.",
  "Every rule you break makes the next decision harder.",
  "Track your behavior, not just your balance.",
  "A clean process produces cleaner data.",
  "Your trading history is a record of decisions under pressure.",
  "You improve when you measure what you actually do.",
  "Awareness is the first step toward changing a trading habit.",
  "The trader who reviews mistakes compounds faster than the trader who hides them.",
  "You cannot improve a pattern you refuse to measure.",
  "Your statistics should challenge your assumptions.",
  "A journal turns experience into evidence.",
  "Review the trade before judging the result.",
  "A profitable mistake is still a mistake.",
  "A losing trade can still be excellent execution.",
  "Judge the process before judging the P&L.",
  "Your P&L tells you what happened. Your journal tells you why.",
  "Patterns become useful when you stop relying on memory.",
  "Emotions become dangerous when they become decision-makers.",
  "Fear does not need to disappear. It needs to stop controlling execution.",
  "After a loss, the next trade still deserves a clean decision.",
  "Revenge trading begins when the previous trade gets a vote on the next one.",
  "Greed turns a good plan into an unnecessary risk.",
  "Overconfidence is often recent success without enough perspective.",
  "The market tests patience more often than intelligence.",
  "Your mindset matters most when your plan is under pressure.",
  "A trader's discipline is most visible after something goes wrong.",
  "Do not trade to recover. Trade when your edge appears.",
  "Protect your mind by protecting your risk.",
  "When risk is controlled, decisions become clearer.",
  "Your account does not need every opportunity.",
  "There will always be another setup. There will not always be another account.",
  "Survival is a prerequisite for compounding.",
  "Capital preservation is a trading strategy.",
  "Small controlled losses leave room for asymmetric outcomes.",
  "The size of the opportunity does not determine the size of the risk.",
  "Never increase risk simply because you want the result faster.",
  "A trader who respects limits gives their edge time to compound.",
  "Your rules are most important when you least want to follow them.",
  "Discipline is choosing predefined risk over current emotion.",
  "If you need hope to hold the trade, the plan is already broken.",
  "A setup is not valid because you want it to be.",
  "Wait for evidence. Execute with conviction. Accept the outcome.",
  "Trading becomes simpler when decisions are made before emotions arrive.",
  "Build rules for the trader you become under pressure.",
  "The purpose of a plan is to remove unnecessary decisions.",
  "Your process should still make sense after a bad day.",
  "The best system is one you can execute consistently.",
  "You do not need more trades. You need better information from the trades you take.",
  "Every review is an opportunity to reduce one recurring mistake.",
  "Progress is often invisible until the data proves it.",
  "Consistency is not perfection. It is controlled repetition.",
  "Mastery is built through thousands of small decisions made correctly.",
  "The trader behind the trades determines what the statistics become.",
  "Your future results are being shaped by today's habits.",
  "Trade less emotionally, review more objectively.",
  "Become the trader your data says you can be.",
  "Become the trader you set out to be.",
] as const

export function getDailyTradingQuote(userId: string, date = new Date()) {
  const dayKey = `${userId}:${date.toISOString().slice(0, 10)}`
  let hash = 0
  for (let index = 0; index < dayKey.length; index += 1) hash = (hash * 31 + dayKey.charCodeAt(index)) | 0
  return tradingQuotes[Math.abs(hash) % tradingQuotes.length]
}
const quoteCountCheck: 100 = tradingQuotes.length
void quoteCountCheck
